baseURL: https://www.example.com/
languageCode: en-us
title: Monteros Landscaping

build:
  buildStats:
    enable: true
  cachebusters:
    - source: 'assets/notwatching/hugo_stats\.json'
      target: css
    - source: '(postcss|tailwind)\.config\.mjs'
      target: css
caches:
  images:
    dir: :cacheDir/images

menu:
  main:
    - name: "Gallery"
      url: "#gallery"
      weight: 1
    - name: "Services"
      url: "#services"
      weight: 2
    - name: "Contact"
      url: "#contact"
      weight: 3

module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json